### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deep0learning** [hsm207/my_unit#1]
Run the following code 

$ python cocogan_train_domain_adaptation.py 
and got the error:

Traceback (most recent call last):
  File "cocogan_train_domain_adaptation.py", line 3, in <module>
    from utils.pipelines import train_input_fn_builder, test_input_fn_builder
  File "/home/user/my_unit/src/utils/pipelines.py", line 3, in <module>
    from datasets.dataset_mnist import dataset_mnist32x32_train, dataset_mnist32x32_test
  File "/home/user/my_unit/src/datasets/dataset_mnist.py", line 30
    print(f'{filename} exists')
                             ^

**Comment by hsm207** [comment]
I'm developing this network using Python 3.6.

The error you got is because I am using the [f-string](https://cito.github.io/blog/f-strings/) feature that is only available on Python 3.6.

Try running the code using Python 3.6

**Comment by hsm207** [comment]
@deep0learning you could also clone the models branch. I've made some commits to make it run on Python 3.4.
